2024-03-24 12:42:44 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:45 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:47 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:48 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:49 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:50 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:52 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:53 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:54 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:57 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:42:58 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:43:00 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:43:01 | MailAssistant.email_providers.google_api.py | Line 739 | ERROR - Error processing the notification: 'dict' object has no attribute 'remove'
2024-03-24 12:51:41 | MailAssistant.email_providers.google_api.py | Line 827 | ERROR - An error occurred when trying to create an email with ID 18e70842931f1ca7: duplicate key value violates unique constraint "MailAssistant_email_provider_id_key"
DETAIL:  Key (provider_id)=(18e70842931f1ca7) already exists.

2024-03-24 12:51:56 | MailAssistant.email_providers.google_api.py | Line 827 | ERROR - An error occurred when trying to create an email with ID 18e708464f9789c2: duplicate key value violates unique constraint "MailAssistant_email_provider_id_key"
DETAIL:  Key (provider_id)=(18e708464f9789c2) already exists.

2024-03-24 12:52:27 | MailAssistant.email_providers.google_api.py | Line 827 | ERROR - An error occurred when trying to create an email with ID 18e7084e82b36400: value too long for type character varying(100)

2024-03-24 12:52:29 | MailAssistant.email_providers.google_api.py | Line 827 | ERROR - An error occurred when trying to create an email with ID 18e7084e82b36400: value too long for type character varying(100)

2024-03-24 12:55:13 | MailAssistant.email_providers.google_api.py | Line 706 | ERROR - SocialAPI entry not found for the email: theohubert45@gmail.com
2024-03-24 13:11:07 | MailAssistant.email_providers.google_api.py | Line 706 | ERROR - SocialAPI entry not found for the email: theohubert45@gmail.com
